apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ros-kinetic-master-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ros-master
    spec:
      nodeSelector:
        dedicated: ros-kinetic
      containers:
      - name: ros-kinetic
        image: ros:kinetic-perception-xenial
        args: ["roscore"]
        ports:
        - containerPort: 11311
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: master-service
spec:
  clusterIP: None
  ports:
  - port: 11311
    targetPort: 11311
    protocol: TCP
  selector:
    app: ros-master
  type: ClusterIP