apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: listener
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: listener
    spec:
      containers:
      -  name: listener
         image: ros:kinetic-perception-xenial
         args: ["rostopic","echo","such_topic"]
         env:
          - name: ROS_HOSTNAME
            value: listener
          - name: ROS_MASTER_URI
            value: http://master-service.default.svc.cluster.local:11311
---
apiVersion: v1
kind: Service
metadata:
  name: listener
spec:
  clusterIP: None
  ports:
  - port: 11311
    targetPort: 11311
    protocol: TCP
  selector:
    app: listener
  type: LoadBalancer